### ISSUE TITLE
不同等级节点问题。

### ISSUE THREAD

**Issue by nrtdadmin** [qinghuas/ss-panel-v3-subscription#1]
我有很多节点是不同等级的，用户看到的是对应等级的节点，如何区分呢？全部节点都再api里面写上，然后能根据不同等级展示订阅？

**Comment by nrtdadmin** [comment]
然后，我出来了，但是没换行，我按照教程一步一步的来操作的!  订阅链接也是更新不到服务器列表

**Comment by qinghuas** [comment]
能提供联系方式我来看一下吗？

**Comment by nrtdadmin** [comment]
你邮箱发我，我给你邮箱发联系方式

**Comment by qinghuas** [comment]
qinghuas@qq.com

**Comment by qinghuas** [comment]
您是使用“节点等级”功能还是使用“节点群组”功能来限制不同用户订阅对应等级/群组服务器？

**Comment by nrtdadmin** [comment]
节点等级

**Comment by nrtdadmin** [comment]
不过很奇怪，我都没看到节点群组和限速在哪设置，改天我再研究那些，先弄订阅

**Comment by qinghuas** [comment]
生成链接时的问题是？1.不能生成 2.能够生成，但是生成的链接涵盖了所有服务器，在这之中有些服务器不应该是该用户应该获取到的服务器，且能够连接服务器 3.能够生成，但是生成的链接涵盖了所有服务器，在这之中有些服务器不应该是该用户应该获取到的服务器，且不能够连接服务器

**Comment by nrtdadmin** [comment]
都不是，访问API，能看到一串字符串，但是吧地址填到订阅里面就是提示失败

**Comment by qinghuas** [comment]
能够通过邮件发我生成的字符串么？看样子像是某些配置错误

**Comment by nrtdadmin** [comment]
给你发邮箱了，麻烦查看一下

**Comment by qinghuas** [comment]
已修复，谢谢反馈。
